version: '3.7'

services:
  mongo:
    container_name: interview-mongo
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/:ro
      - mongodb_data:/data/db

  api:
    container_name: interview-api
    build:
      context: ./api
      dockerfile: dockerfile
    ports:
      - 3001:3001
    volumes:
      - ./api/src:/app/src

  app:
    container_name: interview-app
    build:
      context: ./fe
      dockerfile: dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./fe/src:/fe/src
    links:
      - api


volumes:
  mongodb_data: