version: '3.8'
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./init.js:/init.js
      - mongodb_data:/data/db
    networks:
      - inet
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    depends_on:
      - mongodb
    networks:
      - inet

networks:
  inet:

volumes:
  mongodb_data: