version: '3.7'

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/:ro
      - mongodb_data:/data/db

  api:
    build:
      context: ./api
      dockerfile: dockerfile
    ports:
      - 3001:3001
    volumes:
      - ./api/src:/app/src
    depends_on:
      - mongo

  app:
    build:
      context: ./fe
      dockerfile: dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./fe:/app
      - ./fe/src:/app/src
    depends_on:
      - api


volumes:
  mongodb_data: