version: '3.7'

networks:
  inet:

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/:ro
      - mongodb_data:/data/db
    networks:
      - inet

  api:
    build:
      context: ./api
      dockerfile: dockerfile
    ports:
      - 3001:3001
    volumes:
      - ./api/src:/src
    depends_on:
      - mongo
    networks:
      - inet


volumes:
  mongodb_data: